:source-highlighter: rouge
:sources: ../../test/java/examples
:resources: ../../test/resources
:apache-cassandra-ref: https://cassandra.apache.org

= Configuration

This section covers how to configure Embedded Cassandra.

== Version

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=version]
----

NOTE: Defaults to *4.1.3*.

CAUTION: Since *4.0-beta4*, Windows scripts were removed. https://issues.apache.org/jira/browse/CASSANDRA-16171[CASSANDRA-16171]

== Config Properties

Cassandra config properties, that should be merged with properties from `cassandra.yaml`.
This method is useful, when only a few properties should be overridden in the `cassandra.yaml`.

For example `cassandra.yaml`:

[source,yaml,indent=0]
----
...
storage_port: 7199
native_transport_port: 9042
rpc_port: 9160
client_encryption_options:
   enabled: false
   ...
...
----

The following config properties are used:

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=config-property]
----

The output `cassandra.yaml`:

[source,yaml,indent=0]
----
...
storage_port: 7000
native_transport_port: 9000
rpc_port: 9160
client_encryption_options:
  enabled: true
  ...
...
----

NOTE: Config properties have higher precedence, than properties from the configuration file.

TIP: Use `\` to escape a period character.

== Configuration File

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=config-file]
----

== Startup Parameters

Use system properties to change the Apache Cassandra settings during start up.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=system-property]
----

CAUTION: *-D* prefix should be omitted as it will be added automatically.

== Environment Variables

Adds Cassandra environment variables.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=environment-variable]
----

==  JVM Options

Adds Cassandra native Java Virtual Machine (JVM) Options.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=jvm-options]
----

== Working Directory

The working directory is used as $CASSANDRA_HOME directory.

Before Cassandra starts, the directory will be initialized and customized by `WorkingDirectoryInitializer`
and `WorkingDirectoryCustomizer(s)` respectively.

On Cassandra stop, the directory will be destroyed by `WorkingDirectoryDestroyer` .

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory]
----

NOTE: Defaults to `Files.createTempDirectory("")`.

== Working Directory Customizer

A callback interface to customize a working directory. These customizers are needed to change the working directory before Cassandra starts.
For instance, add some files.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-customizer]
----

== Working Directory Initializer

A strategy interface to initialize the working directory.
The working directory must contain all necessary Cassandra files after the init method has been called.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-initializer]
----

The default implementation is `DefaultWorkingDirectoryInitializer`,
that gets Cassandra directory from the `CassandraDirectoryProvider`
and copies all files from a retrieved directory into the working directory
except *javadoc*, *doc* and *licenses* directories.

By default, `DefaultWorkingDirectoryInitializer` replaces any existing files in the working directory.
If you don't want to replace files in the working directory, you can use `CopyStrategy`.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-initializer-skip-existing]
----

=== Cassandra Directory Provider

`DefaultWorkingDirectoryInitializer` can be configured with a `CassandraDirectoryProvider` implementation.

`CassandraDirectoryProvider` provides a path to Cassandra directory based on a version.

Default implementation is `WebCassandraDirectoryProvider`.

`WebCassandraDirectoryProvider` downloads and extracts Cassandra's archive from the well-known URLs into the download directory.
If the Cassandra's archive has already been extracted into the directory, then this directory will be used, skipping downloading and extracting steps.

== Working Directory Destroyer

A strategy interface to destroy the working directory.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-destroyer]
----

By default, the whole working directory will be deleted.

However, if you don't want to delete a working directory, you can use:

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-destroyer-nothing]
----

== Working Directory Resources

If additional files should be added to the working directory, e.g. `cassandra-rackdc.properties`,
`cassandra-topology.properties`, certificates or something else, the following method can be used.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=add-resource]
----

In the example above, the `ClassPathResource` will be copied into the working directory by the given path.

== Startup Timeout

How long to wait until Cassandra is ready to accept connections.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=startup-timeout]
----

NOTE: Defaults to *2 minutes*.

== Shutdown Hook

Registers shutdown hook for created Cassandra instance.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=shutdown-hook]
----

NOTE: Defaults to **true**.

== Logger

Configure a logger, that consumes Cassandra `STDOUT` and `STDERR` outputs.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=logger]
----

NOTE: Defaults to `Logger.get(Cassandra.class)`.
