:source-highlighter: rouge
:sources: ../../test/java/examples
:resources: ../../test/resources
:apache-cassandra-ref: https://cassandra.apache.org

= Configuration
This section explains how to configure Embedded Cassandra.

== Version
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=version]
----

NOTE: Defaults to *5.0.3*.

== Config Properties

Cassandra configuration properties should be merged with the properties from `cassandra.yaml`.
This method is useful when only a few properties need to be overridden in `cassandra.yaml`.

For example, `cassandra.yaml`:
[source,yaml,indent=0]
----
...
storage_port: 7199
native_transport_port: 9042
client_encryption_options:
   enabled: false
   ...
...
----

The following configuration properties are used:
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=config-property]
----

The resulting `cassandra.yaml`:
[source,yaml,indent=0]
----
...
storage_port: 7000
native_transport_port: 9000
client_encryption_options:
  enabled: true
  ...
...
----

NOTE: Configuration properties override any corresponding properties in the configuration file.

TIP: Use `\` to escape a period.

== Configuration File
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=config-file]
----

== Startup Parameters

Use system properties to change Apache Cassandra settings during startup.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=system-property]
----

CAUTION: The *-D* prefix should be omitted, as it will be added automatically.

== Environment Variables

Define Cassandra environment variables.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=environment-variable]
----

== JVM Options

Define Cassandra's native Java Virtual Machine (JVM) options.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=jvm-options]
----

== Working Directory

The working directory is used as the `$CASSANDRA_HOME` directory.

Before Cassandra starts, the directory will be initialized by the `WorkingDirectoryInitializer` and customized by one or more `WorkingDirectoryCustomizer` instances.

When Cassandra stops, the directory will be destroyed by the `WorkingDirectoryDestroyer`.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory]
----
NOTE: Defaults to `Files.createTempDirectory("")`.

== Working Directory Customizer

A callback interface to customize the working directory.
These customizations happen before Cassandra starts.
For example, you can add specific files.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-customizer]
----

== Working Directory Initializer

A strategy interface for initializing the working directory.
After the `init` method is invoked, the working directory must contain all necessary Cassandra files.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-initializer]
----

The default implementation, `DefaultWorkingDirectoryInitializer`, retrieves the Cassandra directory from the `CassandraDirectoryProvider` and copies all files into the working directory, except *javadoc*, *doc*, and *licenses* directories.

By default, `DefaultWorkingDirectoryInitializer` replaces any existing files in the working directory.
To avoid replacing files, use a `CopyStrategy`.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-initializer-skip-existing]
----

=== Cassandra Directory Provider

The `DefaultWorkingDirectoryInitializer` can be configured with a `CassandraDirectoryProvider` implementation.

A `CassandraDirectoryProvider` supplies the path to the Cassandra directory based on the version.

The default implementation is `WebCassandraDirectoryProvider`.
It downloads and extracts Cassandra archives from known URLs into the download directory.
If the archive has already been extracted, then the existing directory is used, skipping the download and extraction steps.

== Working Directory Destroyer

A strategy interface for destroying the working directory.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-destroyer]
----

By default, the entire working directory is deleted.

To preserve the working directory, use the following approach:
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=working-directory-destroyer-nothing]
----

== Working Directory Resources

To add additional files (e.g., `cassandra-rackdc.properties`, `cassandra-topology.properties`, certificates, etc.) to the working directory, use this method:
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=add-resource]
----

In the example above, the `ClassPathResource` is copied to the working directory at the specified path.

== Startup Timeout

Set the duration to wait until Cassandra is ready to accept connections.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=startup-timeout]
----
NOTE: Defaults to *2 minutes*.

== Shutdown Hook

Registers a shutdown hook for the created Cassandra instance.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=shutdown-hook]
----
NOTE: Defaults to **true**.

== Logger

Configure a logger to consume Cassandra's `STDOUT` and `STDERR` outputs.
[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=logger]
----
NOTE: Defaults to `LoggerFactory.getLogger(Cassandra.class)`.
