:source-highlighter: rouge
:sources: ../java
:resources: ../resources

= F.A.Q

== What are OSs supported by Embedded Cassandra?

Embedded Cassandra is tested under the `ubuntu-latest`, `macos-latest` and `windows-latest` platforms.

== What are versions supported by Embedded Cassandra?

Embedded Cassandra project is tested for `2.X.X` - `4.X.X` Cassandra versions.

|===
|OS |Version Range

|Windows
|2.X.X - 4.0-beta3

|OSX
|2.X.X - 4.X.X

|Linux
|2.X.X - 4.X.X
|===

CAUTION: Since *4.0-beta4*, Windows scripts were removed https://issues.apache.org/jira/browse/CASSANDRA-16171[CASSANDRA-16171]

== What are compile dependencies used by Embedded Cassandra?

Embedded Cassandra has only two compile dependencies:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<dependecies>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>{commons-compress-version}</version>
    </dependency>
    <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>{snakeyaml-version}</version>
    </dependency>
</dependecies>
----

== Is it possible to start more than one Cassandra instance?

Yes, it is possible. Both instances must be started on different ports.

== Which are URLs used for downloading Apache Cassandra?

It depends on the version, if it is the latest release, it will be downloaded from
https://downloads.apache.org/cassandra/. For older versions, https://archive.apache.org/dist/cassandra/  is used.

== Where are the files downloaded?

By default, files are downloaded into *~/.embedded-cassandra/cassandra* directory
