:source-highlighter: rouge
:sources: ../../test/java/examples
:resources: ../../test/resources

= F.A.Q

== What operating systems are supported by Embedded Cassandra?

Embedded Cassandra is tested on the `ubuntu-latest` and `macos-latest` platforms.

== What versions are supported by Embedded Cassandra?

The Embedded Cassandra project is tested with Cassandra versions `>= 4.x.x`.

== What are the compile dependencies used by Embedded Cassandra?

Embedded Cassandra has the following compile dependencies:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>{commons-compress-version}</version>
    </dependency>
    <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>{snakeyaml-version}</version>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>{logback-classic-version}</version>
    </dependency>
</dependencies>
----

== Is it possible to start more than one Cassandra instance?

Yes, it is possible. Both instances must be started on different ports.

== What are the URLs used for downloading Apache Cassandra?

The URLs depend on the version.
For the latest releases, it will be downloaded from:
https://downloads.apache.org/cassandra/.
For older versions, the following URL is used: https://archive.apache.org/dist/cassandra/.

== Where are the files downloaded?

By default, files are downloaded into the *~/.embedded-cassandra/* directory.
