:source-highlighter: rouge
:sources: ../java
:resources: ../resources

= F.A.Q

== What OSs does Embedded Cassandra support?

Embedded Cassandra is tested under the `ubuntu-latest`, `macos-latest` and `windows-latest` platforms.

== What Cassandra versions are supported by Embedded Cassandra?

Embedded Cassandra project is tested for `2.X.X` - `4.X.X` Cassandra versions.

== What compile dependencies are used by Embedded Cassandra?

Embedded Cassandra has only two compile dependencies:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<dependecies>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>{commons-compress-version}</version>
    </dependency>
    <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>{snakeyaml-version}</version>
    </dependency>
</dependecies>
----

== Is it possible to start more than one Cassandra instance?

Yes, it is possible. Both instances must be started on different ports.

== From which URLs Apache Cassandra is downloaded?

It depends on the version, if it the latest release, it will be downloaded from
https://downloads.apache.org/cassandra/ if it is previous release, it will be downloaded from
https://archive.apache.org/dist/cassandra/

== Where are the files downloaded?

By default, files are downloaded into *~/.embedded-cassandra/cassandra* directory
