:source-highlighter: rouge
:sources: ../java
:resources: ../resources

= How-to?

This section provides answers to some common ‘how do I do that...’ questions
that often arise when using Embedded Cassandra.

== Configuration File

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=config-file-system-property]
----

== Client Encryption Options

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=client-encryption-options]
----

== Authorization and Authentication

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=authenticator]
----
<1> Creates a superuser immediately.

NOTE: Default superuser credential is _user_: **cassandra** _password_: **cassandra**

== Random Ports

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=random-ports]
----

NOTE: A port number of *0* means that the port number is automatically allocated,
typically from an ephemeral port range.

== Simple Seed Provider

It is possible programmatically configure `org.apache.cassandra.locator.SimpleSeedProvider` via
`SimpleSeedProviderConfigurator` configurator.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=configure-seeds]
----
<1>  A port number of *0* means that the port number is replaced by either `cassandra.storage_port` or `storage_port`.

== Proxy

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=proxy]
----

== Add a lib to Cassandra Classpath

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=custom-classpath]
----

== JUnit4

[source,java,indent=0]
----
include::{sources}/CassandraJUnit4Example.java[tag=code]
----

== JUnit5

[source,java,indent=0]
----
include::{sources}/CassandraJUnit5Example.java[tag=code]
----
