:source-highlighter: rouge
:sources: ../java
:resources: ../resources
:apache-cassandra-ref: https://cassandra.apache.org

= How-to?

This section provides answers to some common ‘how do I do that...’ questions
that often arise when using Embedded Cassandra.

== Client Encryption Options

In order to enable a client SSL communication, `client_encryption_options` should be configured:

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=client-encryption-options]
----

NOTE: See {apache-cassandra-ref}/doc/latest/operating/security.html#tls-ssl-encryption

== Authorization and Authentication

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=authenticator]
----
<1> Creates a superuser immediately.

NOTE: Default superuser credential is _user_: **cassandra** _password_: **cassandra**.

NOTE: See {apache-cassandra-ref}/doc/latest/operating/security.html#authentication

== Random Ports

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=random-ports]
----

NOTE: A port number of *0* means that the port number is automatically allocated,
typically from an ephemeral port range.

NOTE: *0* ports also can be used in the configuration file.

== Simple Seed Provider

It is possible to configure `org.apache.cassandra.locator.SimpleSeedProvider` via
`SimpleSeedProviderConfigurator` configurator.

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=configure-seeds]
----
<1>  A port number of *0* means that the port number is replaced by either `cassandra.storage_port` or `storage_port`.

== Add libs to classpath

If you want to add some custom libraries into Cassandra's classpath,
you can add them this via:

[source,java,indent=0]
----
include::{sources}/CassandraExamples.java[tag=custom-classpath]
----
