[[features]]
= Features

This section describes key features that you may want to use and customize.

[[features-configuration]]
== Configuration

This section covers how to configure Embedded Cassandra.

[[features-configuration-artifact]]
=== Configure Version

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraVersion.java[tag=source]
----

TIP: Default version is *3.11.4*

[[features-configure-configuration-file]]
=== Configure Config

Sets Cassandra's configuration file (`cassandra.yaml`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraConfig.java[tag=source]
----

[[features-configure-properties]]
=== Configure Config Properties

These properties override any Cassandra's properties in the (`cassandra.yaml`).

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraConfigProperties.java[tag=source]
----

TIP: More about configuration properties {apache-cassandra-configuration-ref}[here]

[[features-configure-rack-file]]
=== Configure Rack Config

Sets Cassandra's rack properties (`cassandra-rackdc.properties`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraRackConfig.java[tag=source]
----

[[features-configure-topology-file]]
=== Configure Topology Config

Sets Cassandra's topology properties (`cassandra-topology.properties`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraTopologyConfig.java[tag=source]
----

[[features-configure-system-properties]]
=== Configure System Properties

System properties that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraSystemProperties.java[tag=source]
----

TIP: More about startup parameters you can read {apache-cassandra-parameters-ref}[here]

[[features-configure-environment-variables]]
=== Configure Environment Variables

Environment variables that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraEnvironmentVariables.java[tag=source]
----

[[features-configure-jvm-options]]
=== Configure JVM Options

JVM options that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraJvmOptions.java[tag=source]
----

[[features-configure-java-home]]
=== Configure Java Home

Sets the Java Home. This home used by Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraJavaHome.java[tag=source]
----

[[features-configuration-ssl]]
=== Configure SSL

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraSsl.java[tag=source]
----

[[features-configuration-auth]]
=== Configure Authentication/Authorization

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraAuthentication.java[tag=source]
----

[[configuration-ports]]
=== Configure Ports

By default, EmbeddedCassandra is running on default ports.
There are several methods that can be used to set ports, such as `setPort(int)`.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraPorts.java[tag=source]
----

TIP: Use `0` for a random port.

[[features-configure-proxy]]
=== Configure Proxy

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraProxy.java[tag=source]
----

[[features-exposed-properties]]
== Exposed Properties

The following properties will be exposed as `System Properties` after Cassandra has started:

* `embedded.cassandra.version`
* `embedded.cassandra.address`
* `embedded.cassandra.port`
* `embedded.cassandra.ssl-port`
* `embedded.cassandra.rpc-port`

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraExposedProperties.java[tag=source]
----

TIP: Exposed properties can be disabled by `EmbeddedCassandraFactory.setExposeProperties(false)`

[[features-cql]]
== CQL Support

Embedded Cassandra project provides high-level support for `CQL` scripts.

[[features-cql-maven]]
=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-cql</artifactId>
            <version>{project-version}</version>
        </dependency>
----

[[features-cql-gradle]]
=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-cql', version: '{project-version}'
----

=== Load Cql Statements from __Resource__

CQL statements can be easily loaded from a `Resource` via __static method__ `ofResource`:

[source,java,indent=0]
----
include::{test-sources}/examples/cql/CqlScripts.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

TIP: More about *CQL* you can find {apache-cassandra-cql-ref}[here]
