= Features

This section describes key features that you may want to use and customize.

== Configuration

This section covers how to configure Embedded Cassandra.

=== Configure Version

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraVersion.java[tag=source]
----

TIP: Default version is *3.11.4*

=== Configure Config

Sets Cassandra's configuration file (`cassandra.yaml`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraConfig.java[tag=source]
----

=== Configure Config Properties

These properties override any Cassandra's properties in the (`cassandra.yaml`).

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraConfigProperties.java[tag=source]
----

TIP: More about configuration properties {apache-cassandra-configuration-ref}[here]

=== Configure Rack Config

Sets Cassandra's rack properties (`cassandra-rackdc.properties`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraRackConfig.java[tag=source]
----

=== Configure Topology Config

Sets Cassandra's topology properties (`cassandra-topology.properties`)

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraTopologyConfig.java[tag=source]
----

=== Configure System Properties

System properties that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraSystemProperties.java[tag=source]
----

TIP: More about startup parameters you can read {apache-cassandra-parameters-ref}[here]

=== Configure Environment Variables

Environment variables that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraEnvironmentVariables.java[tag=source]
----

=== Configure JVM Options

JVM options that should be passed to Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraJvmOptions.java[tag=source]
----

=== Configure Java Home

Sets the Java Home. This home used by Cassandra's process.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraJavaHome.java[tag=source]
----

=== Configure SSL

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraSsl.java[tag=source]
----

=== Configure Authentication/Authorization

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraAuthentication.java[tag=source]
----

=== Configure Ports

By default, EmbeddedCassandra is running on default ports. There are several methods that can be used to set ports.

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraPorts.java[tag=source]
----

TIP: Use `0` for a random port.

=== Configure Proxy

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraProxy.java[tag=source]
----

== Exposed Properties

The following properties will be exposed as `System Properties` after Cassandra has started:

* `embedded.cassandra.version`
* `embedded.cassandra.address`
* `embedded.cassandra.port`
* `embedded.cassandra.ssl-port`
* `embedded.cassandra.rpc-port`

[source,java,indent=0]
----
include::{test-sources}/examples/configuration/CassandraExposedProperties.java[tag=source]
----

TIP: Exposed properties can be disabled by `EmbeddedCassandraFactory.setExposeProperties(false)`

== CQL Support

Embedded Cassandra project provides high-level support for `CQL` scripts.

=== Load Cql Statements

CQL statements can be easily loaded from various sources.

[source,java,indent=0]
----
include::{test-sources}/examples/cql/CqlDataSetExample.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

TIP: More about *CQL* you can find {apache-cassandra-cql-ref}[here]
