= Getting Started

== Overview

The goal of this document is to provide comprehensive reference documentation for programmers using Embedded Cassandra.

=== Introducing

Embedded Cassandra provides an easy way to start and stop {apache-cassandra-ref}[Apache Cassandra] as an embedded database.

Primary features are:

* Support different versions.
* Supports multiple platforms: `Windows`, `Linux` and `OSX`.
* Provides different extensions for popular frameworks: `JUnit4`, `JUnit5`, `TestNG`, `Spring Framework`.

=== Getting Help

Ask Embedded Cassandra related questions on https://stackoverflow.com/questions/tagged/embedded-cassandra[Stack Overflow].

=== Issues

Embedded Cassandra uses GitHub's issue tracking system to report bugs and feature requests.
If you want to raise an issue, please follow this {github-issues}[link]

=== License

Embedded Cassandra is released under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0]

=== Get Source

Embedded Cassandra repository can be found {github-code}[here]

=== Build Source

Embedded Cassandra can be easily built with the https://github.com/takari/maven-wrapper[maven wrapper].
You also need `JDK 1.8`.

[source,bash]
----
$ ./mvnw clean verify
----

=== Modules

[cols="m,m"]
|===

|Name |Description
| embedded-cassandra | This module contains items that allows the Apache Cassandra to be started and stopped.
| embedded-cassandra-annotations | This module contains JSR305 annotations.
| embedded-cassandra-api |This module contains Embedded Cassandra API classes.
| embedded-cassandra-cql |This module contains `Cql` Support Classes.
| embedded-cassandra-commons |This module contains Embedded Cassandra common classes.
| embedded-cassandra-docs |This module contains Embedded Cassandra Reference Documentation.
| embedded-cassandra-junit4-test |This module contains Embedded Cassandra JUnit4 classes.
| embedded-cassandra-junit5-test |This module contains Embedded Cassandra JUnit5 classes.
| embedded-cassandra-spring-test |This module contains Embedded Cassandra Spring classes.
| embedded-cassandra-testng-test |This module contains Embedded Cassandra TestNG classes.
| embedded-cassandra-mock |This module contains Embedded Cassandra *Mock* classes.

|===

=== Contributing to Embedded Cassandra

Embedded Cassandra welcomes contributions from everyone.

Contributions to Embedded Cassandra should be made in the form of `GitHub pull requests`.

==== Pull Request Checklist

* Branch from the `master` branch and, if needed, rebase to the current `master` branch before submitting your pull request.
* Commits should be as small as possible.
* Add tests relevant to the fixed bug or new feature.

== Quick Start

=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra</artifactId>
            <version>{project-version}</version>
        </dependency>
----

=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra', version: '{project-version}'
----

=== First example

The Apache Cassandra can be started using the following lines of code:

[source,java,indent=0]
----
include::{test-sources}/examples/FirstExample.java[tag=source]
----

