= Using JUnit5

Cassandra can be easily started using `CassandraExtension`.
This extension allows the Cassandra to be started and stopped.
Cassandra will be started only once before any test method is executed and stopped after the last test method has executed.

== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-junit5-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-junit5-test', version: '{project-version}'
----

== Run Cassandra JUnit5

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/CassandraJUnit5Tests.java[tag=source]
----

The following properties will be added to `System Properties` after Cassandra has started:

* `embedded.cassandra.version`
* `embedded.cassandra.address`
* `embedded.cassandra.port`
* `embedded.cassandra.ssl-port`
* `embedded.cassandra.rpc-port`


WARNING: By default, `CassandraExtension` runs Cassandra on the random ports.

== Customize Default Cassandra Factory

In the following example, there is a showcase of how to change Cassandra's port using (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/customizer/CassandraDefaultFactoryCustomizerJUnit5Tests.java[tag=source]
----

== Configure Custom Cassandra Factory

Besides that, custom `CassandraFactory` also can be used to control the `Cassandra` instance.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/factory/CassandraCustomFactoryJUnit5Tests.java[tag=source]
----

== Configure Cql Scripts

`Cassandra` can be initialized with `CqlDataSet`. `CQL` statements will be executed immediately after Cassandra start.
`CassandraExtension` has a factory method to set a `CqlDataSet`.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/cql/CassandraCqlDataSetJUnit5Tests.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

== Configure Custom Cassandra Connection Factory

`CassandraConnection` which is provided by `CassandraExtension` can be configured via `CassandraConnectionFactory`.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/connection/CassandraConnectionJUnit5Tests.java[tag=source]
----

