= Using JUnit4

Cassandra can be started via `CassandraRule`. `CassandraRule` is `TestRule` that allows the Cassandra to be started and stopped.
Cassandra declared as static field with a `@ClassRule` annotation will be started only once before any test method is executed and stopped after the last test method has executed.
Cassandra declared as instance field with a `@Rule` annotation will be started and stopped for every test method.

== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-junit4-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-junit4-test', version: '{project-version}'
----

== Run Cassandra JUnit4

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/CassandraJUnit4Tests.java[tag=source]
----

The following properties will be added to `System Properties` after Cassandra has started:

* `embedded.cassandra.version`
* `embedded.cassandra.address`
* `embedded.cassandra.port`
* `embedded.cassandra.ssl-port`
* `embedded.cassandra.rpc-port`


== Customize Default Cassandra Factory

Default `EmbeddedCassandraFactory` can be customized via (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/customizer/CassandraDefaultFactoryCustomizerJUnit4Tests.java[tag=source]
----

== Configure Custom Cassandra Factory

There is also possible to use your own `CassandraFactory`.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/factory/CassandraCustomFactoryJUnit4Tests.java[tag=source]
----

== Configure Cql Scripts

`CassandraRule` provides a way to initialize Apache Cassandra with `CqlDataSet`.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/cql/CassandraCqlDataSetJUnit4Tests.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

== Configure Custom Cassandra Connection Factory

`CassandraConnection` which is provided by `CassandraRule` can be configured via `CassandraConnectionFactory`.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/connection/CassandraConnectionJUnit4Tests.java[tag=source]
----
