= Using Spring Test

For running Apache Cassandra using Spring Test, `@EmbeddedCassandra` annotation has to be used.
This annotation allows the Cassandra to be started and stopped.

== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-spring-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-spring-test', version: '{project-version}'
----

== Run Cassandra Spring Test

[source,java,indent=0]
----
include::{test-sources}/examples/spring/CassandraSpringTests.java[tag=source]
----

The following properties will be added to `Environment` after Cassandra has started:

* `embedded.cassandra.version`
* `embedded.cassandra.address`
* `embedded.cassandra.port`
* `embedded.cassandra.ssl-port`
* `embedded.cassandra.rpc-port`

WARNING: By default, `@EmbeddedCassandra` runs Cassandra on the random ports.

== Configure Custom Cassandra Factory

It is possible to register you own `CassandraFactory` to control Cassandra instance.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/factory/CassandraCustomFactoryTests.java[tag=source]
----

== Customize Default Cassandra Factory

Additional to the above, there is also possible to register `CassandraFactoryCustomizer<T>` `@Bean`(s) to customize a default
`EmbeddedCassandraFactory` before the `Cassandra` itself is started.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/customizer/CassandraDefaultFactoryCustomizerSpringTests.java[tag=source]
----

== Configure Cql Scripts

CQL Scripts are executed by `CassandraConnection`. By default, `CassandraConnection` implementation is detected based on the classpath,
however, `CassandraConnectionFactory` can be registered as a `@Bean` to control scripts execution.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/cql/CassandraCqlSpringTests.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

== Configure Custom Cassandra Connection Factory

`CassandraConnectionFactory` bean can be registered to control `CassandraConnection` isntance.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/connection/CassandraConnectionSpringTests.java[tag=source]
----

== Using Spring Boot Test

There is no much difference between `Spring Boot Test` and `Spring Test`, hence, to start Cassandra, `@EmbeddedCassandra` can be used.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/boot/CassandraSpringBootTests.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

TIP: `${embedded.cassandra.port}` and `${embedded.cassandra.address}` properties are exposed by `@EmbeddedCassandra`.
