[[testing]]
= Testing

Embedded Cassandra provides a number of extensions to help when testing your application.

[[testing-junit5]]
== Using JUnit5

Cassandra can be easily started using `CassandraExtension`.
This extension allows the Cassandra to be started and stopped.
Cassandra will be started only once before any test method is executed and stopped after the last test method has executed.

[[testing-junit5-maven]]
=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-junit5-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

[[testing-junit5-gradle]]
=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-junit5-test', version: '{project-version}'
----

=== Run Cassandra with JUnit5

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/CassandraTests.java[tag=source]
----

WARNING: `CassandraExtension` configures Cassandra on the random ports.

In contrast to `@ExtendWith` which is used to register extensions declaratively, `@RegisterExtension`
can be used to register an extension programmatically to pass arguments to the `CassandraExtension's` constructor.

=== Customize Default Cassandra Factory

In the following example, there is a showcase of how to change Cassandra's port using (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/customizer/CassandraTests.java[tag=source]
----

=== Use Custom Cassandra Factory

Besides that, custom `CassandraFactory` also can be used to control the `Cassandra` instance.

[source,java,indent=0]
----
include::{test-sources}/examples/junit5/configuration/factory/CassandraTests.java[tag=source]
----

[[testing-junit4]]
== Using JUnit4

Cassandra can be started via `CassandraRule`. `CassandraRule` is `TestRule` that allows the Cassandra to be started and stopped.
Cassandra declared as static field with a `@ClassRule` annotation will be started only once before any test method is executed and stopped after the last test method has executed.
Cassandra declared as instance field with a `@Rule` annotation will be started and stopped for every test method.

[[testing-junit4-maven]]
=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-junit4-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

[[testing-junit4-gradle]]
=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-junit4-test', version: '{project-version}'
----

=== Run Cassandra with JUnit4

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/CassandraTests.java[tag=source]
----

WARNING: `CassandraRule` with a default constructor configures Cassandra on the random ports.

=== Customize Default Cassandra Factory

Default `CassandraFactory` can be customized via (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/customizer/CassandraTests.java[tag=source]
----

=== Use Custom Cassandra Factory

There is also possible to use your own `CassandraFactory`. Just pass it to the constructor.

[source,java,indent=0]
----
include::{test-sources}/examples/junit4/configuration/factory/CassandraTests.java[tag=source]
----

[[testing-testng]]
== Using TestNG

To run Cassandra using `TestNG`, `AbstractCassandraTests` class has to be extended.
`AbstractCassandraTests` class allows the Cassandra to be started and stopped.
Cassandra will be started only once before any test method is executed and stopped after the last test method has executed.

[[testing-testng-maven]]
=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-testng-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

[[testing-testng-gradle]]
=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-testng-test', version: '{project-version}'
----

=== Run Cassandra with TestNG

[source,java,indent=0]
----
include::{test-sources}/examples/testng/CassandraTests.java[tag=source]
----

WARNING: `AbstractCassandraTests` with a default constructor configures Cassandra on the random ports.

=== Customize Default Cassandra Factory

`AbstractCassandraTests` also provides a way to customize a default `CassandraFactory` via (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/customizer/CassandraTests.java[tag=source]
----

=== Use Custom Cassandra Factory

The same as for `JUnit4` and `JUnit5` it is possible to set your own `CassandraFactory` through the constructor.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/factory/CassandraTests.java[tag=source]
----

[[testing-spring]]
== Using Spring Test

For running Apache Cassandra using Spring Test, `@EmbeddedCassandra` annotation has to be used.
This annotation allows the Cassandra to be started and stopped.
Cassandra will be registered as a bean named
`Cassandra.class.getName()`.
By default, `EmbeddedCassandraFactory` used, which is configured to use random ports.
However, it still exists a way to register your own `CassandraFactory` to control Cassandra instance by your own wish.

[[testing-spring-maven]]
=== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-spring-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

[[testing-spring-gradle]]
=== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-spring-test', version: '{project-version}'
----

=== Run Cassandra with Spring Test

[source,java,indent=0]
----
include::{test-sources}/examples/spring/CassandraTests.java[tag=source]
----

WARNING: By default, `@EmbeddedCassandra` configures Cassandra on the random ports.

=== Use Custom Cassandra Factory

It is possible to register you own factory to control Cassandra instance.
Here is a small example:

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/factory/CassandraTests.java[tag=source]
----

=== Customize Default Cassandra Factory

Additional to the above, there is also possible to register `CassandraFactoryCustomizer<T>` beans to customize a default
`EmbeddedCassandraFactory` before the `Cassandra` itself is started.

[source,java,indent=0]
----
include::{test-sources}/examples/spring/configuration/customizer/CassandraTests.java[tag=source]
----
