= Using TestNG

To start Cassandra with `TestNG`, `AbstractCassandraTests` class has to be extended.
`AbstractCassandraTests` class allows the Cassandra to be started and stopped.
Cassandra will be started only once before any test method is executed and stopped after the last test method has executed.

== Maven

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-testng-test</artifactId>
            <version>{project-version}</version>
        </dependency>
----

== Gradle

[source,groovy,indent=0,subs="verbatim,quotes,attributes"]
----
compile group: 'com.github.nosan', name: 'embedded-cassandra-testng-test', version: '{project-version}'
----

== Run Cassandra TestNG

[source,java,indent=0]
----
include::{test-sources}/examples/testng/CassandraTestNGTests.java[tag=source]
----

WARNING: By default, `AbstractCassandraTests` runs Cassandra on the random ports.

== Customize Default Cassandra Factory

`AbstractCassandraTests` also provides a way to customize a default `CassandraFactory` via (`CassandraFactoryCustomizer<T>`) customizers.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/customizer/CassandraDefaultFactoryCustomizerTestNGTests.java[tag=source]
----

== Configure Custom Cassandra Factory

The same as for `JUnit4` and `JUnit5` it is possible to set your own `CassandraFactory` through the constructor.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/factory/CassandraCustomFactoryTestNGTests.java[tag=source]
----

== Configure Cql Scripts

`AbstractCassandraTests` provides a smooth way to initialize Cassandra with `CqlDataSet`.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/cql/CassandraCqlDataSetTestNGTests.java[tag=source]
----

.schema.cql
[source,cql,indent=0]
----
include::{test-resources}/schema.cql[]
----

== Configure Custom Cassandra Connection Factory

`CassandraConnection` which is provided by `AbstractCassandraTests` can be configured via `CassandraConnectionFactory`.

[source,java,indent=0]
----
include::{test-sources}/examples/testng/configuration/connection/CassandraConnectionTestNGTests.java[tag=source]
----
